/**
 * Postgres schema for the DriftWatch control plane.
 *
 * This is the durable store the roadmap's step 2 called for, and it replaces
 * BOTH previous backends rather than sitting alongside them: `PostgresStateStore`
 * implements the whole `StateStore` interface, so a deployment picks exactly one
 * backend and there is never a question of which system holds a given record.
 * Redis remains supported for anyone who wants it, but is no longer required.
 *
 * ## Conventions, and why
 *
 * **Timestamps are `bigint` epoch-ms, not `timestamptz`.** Every domain type in
 * @driftwatch/sdk (`Approval.createdAt`, `AuditEvent.at`, ...) is a `number`, and
 * those types are shared with the browser bundle and the published SDK. Storing
 * native timestamps would mean a Date<->number conversion at every one of the ~40
 * boundaries below, each one a place to silently lose milliseconds or shift a
 * zone. `bigint` round-trips losslessly and epoch-ms stays inside
 * `Number.MAX_SAFE_INTEGER` until the year 287396.
 *
 * **Status/action columns are `text().$type<Union>()`, not pg enums.** `ACTION_TYPES`
 * and `AUDIT_ACTIONS` are lists that grow with the product. A pg enum turns every
 * addition into a migration that historically could not run inside a transaction,
 * and removal is not supported at all. Text plus a compile-time union gives the
 * same authoring safety with none of the migration cost; zod already validates
 * anything arriving from outside the process.
 *
 * **`organizationId` is on every tenant-scoped table from day one.** Nothing uses
 * it yet — self-hosted deployments run entirely inside `DEFAULT_ORGANIZATION_ID`.
 * It is here because retrofitting multi-tenancy onto a populated audit log and
 * key store is one of the worst migrations there is, and an unused column costs
 * nothing. See the roadmap discussion: whether DriftWatch is ever hosted decides
 * if this is needed, and that decision does not have to be made today for the
 * column to be cheap.
 */
import {
  bigint,
  bigserial,
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import type {
  ActionCategory,
  ActionOutcome,
  ActionType,
  AgentStatus,
  ApiKeyScope,
  ApprovalStatus,
  AuditAction,
  AgentConfig,
  DriftSeverity,
  ToolCallPolicyRule,
} from '@driftwatch/sdk';

/**
 * The organization every record belongs to in a single-tenant (self-hosted)
 * deployment. Seeded at boot alongside the admin user — see db/seed.ts.
 */
export const DEFAULT_ORGANIZATION_ID = 'default';

// --- tenancy ----------------------------------------------------------------

export const organizations = pgTable('organizations', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: bigint('created_at', { mode: 'number' }).notNull(),
});

// --- humans -----------------------------------------------------------------
//
// Users, sessions, accounts and verification tokens are NOT defined here. They
// are owned by better-auth and live in ./auth-schema.ts, generated by its CLI so
// the columns cannot drift from what the library actually queries. Hand-writing
// them would mean re-deriving another project's schema by hand and re-checking
// it on every upgrade.
//
// Two consequences worth knowing:
//   - Password hashing is better-auth's (scrypt), NOT the sha256 used for API
//     keys in @driftwatch/sdk. That asymmetry is deliberate: a minted API token
//     is 24 bytes of CSPRNG output where a fast indexable hash is both
//     sufficient and necessary for O(1) lookup, while a human password is
//     low-entropy and needs a deliberately slow KDF. Reaching for
//     `hashApiKeyToken` on a password would be a real vulnerability.
//   - `organizationId` and `role` are attached to better-auth's user table as
//     additionalFields (see auth/auth.ts), so a user carries the same tenancy
//     column as every table below.

// --- agent registry ---------------------------------------------------------

/**
 * The agent registry. This row holds the CODE-DECLARED BASELINE — what the SDK
 * pushed at registration — and `agent_overrides` holds what an operator changed
 * in the console. Effective config is baseline <- override, resolved in
 * db/resolve-agent.ts.
 *
 * Keeping them in separate tables rather than as parallel columns is what makes
 * "revert to code" a DELETE and makes "is this overridden?" answerable without
 * comparing every field. It is also the only shape in which a redeploy can
 * update the baseline WITHOUT silently discarding an operator's emergency edit.
 */
export const agents = pgTable(
  'agents',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    name: text('name').notNull(),
    owner: text('owner'),
    serviceName: text('service_name'),
    createdAt: bigint('created_at', { mode: 'number' }).notNull(),
    guardrails: jsonb('guardrails').$type<Partial<AgentConfig>>(),
    guardrailsSource: text('guardrails_source'),
    toolNames: jsonb('tool_names').$type<string[]>(),
    driftDetectionEnabled: boolean('drift_detection_enabled'),
    toolPolicies: jsonb('tool_policies').$type<ToolCallPolicyRule[]>(),
    toolPoliciesSource: text('tool_policies_source'),
    /**
     * Last time an SDK client pushed this baseline. Null for an agent created
     * through the console, which is how the UI can say "declared in code" vs
     * "created here" without a second column.
     */
    lastSyncedAt: bigint('last_synced_at', { mode: 'number' }),
    /** SDK version that last synced, for support triage. */
    sdkVersion: text('sdk_version'),
  },
  (table) => [index('agents_org_idx').on(table.organizationId)],
);

/**
 * Console-authored overrides layered over an agent's code-declared baseline.
 *
 * Only the fields an operator actually changed are non-null, so the merge can
 * distinguish "explicitly set to empty" from "not overridden" — which a single
 * merged blob could not. Deleting the row is "revert to code".
 */
export const agentOverrides = pgTable('agent_overrides', {
  agentId: text('agent_id')
    .primaryKey()
    .references(() => agents.id, { onDelete: 'cascade' }),
  organizationId: text('organization_id')
    .notNull()
    .references(() => organizations.id),
  guardrails: jsonb('guardrails').$type<Partial<AgentConfig>>(),
  toolNames: jsonb('tool_names').$type<string[]>(),
  toolPolicies: jsonb('tool_policies').$type<ToolCallPolicyRule[]>(),
  driftDetectionEnabled: boolean('drift_detection_enabled'),
  updatedAt: bigint('updated_at', { mode: 'number' }).notNull(),
  /** Principal id that made the edit; joins to the audit log. */
  updatedBy: text('updated_by').notNull(),
});

/**
 * Tool metadata synced from the SDK at registration.
 *
 * Descriptive only — nothing is gated because a tool is marked destructive.
 * `fields` is what makes field-scoped policy authoring possible at all: it is
 * derived from the tool's own input schema so the console's policy editor and
 * the SDK's compile-time autocomplete come from one source.
 */
export const agentTools = pgTable(
  'agent_tools',
  {
    agentId: text('agent_id')
      .notNull()
      .references(() => agents.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    description: text('description').notNull().default(''),
    /** Dot-paths derived from the tool's input schema. */
    fields: jsonb('fields').$type<string[]>().notNull(),
    sensitiveFields: jsonb('sensitive_fields').$type<string[]>(),
    readOnly: boolean('read_only').notNull().default(false),
    destructive: boolean('destructive').notNull().default(false),
    idempotent: boolean('idempotent').notNull().default(false),
    syncedAt: bigint('synced_at', { mode: 'number' }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.agentId, table.name] })],
);

/**
 * Mutable runtime posture, split from the registry because it changes far more
 * often.
 *
 * Deliberately NO foreign key to `agents`, unlike `agent_overrides` and
 * `agent_tools`. `MemoryStateStore.setAgentState` accepts any id and
 * `getAgentState` synthesises a default for an unknown one, and the two backends
 * have to behave identically or "pick exactly one backend" is a false promise —
 * the store conformance suite runs the same assertions against both. Referential
 * integrity here would buy little anyway: an orphaned state row is inert.
 */
export const agentState = pgTable('agent_state', {
  agentId: text('agent_id').primaryKey(),
  organizationId: text('organization_id')
    .notNull()
    .references(() => organizations.id),
  status: text('status').$type<AgentStatus>().notNull(),
  activeModel: text('active_model'),
  activeVersion: integer('active_version').notNull(),
  updatedAt: bigint('updated_at', { mode: 'number' }).notNull(),
  reason: text('reason'),
});

// --- approvals --------------------------------------------------------------

/**
 * Loop 2: a control action (pause/rollback/switch_model) awaiting a human.
 *
 * The `(agent_id, status, created_at)` index covers the only listing query —
 * resolved approvals are read by id, so the pending set stays cheap to scan
 * while the table grows without bound.
 *
 * `seq` exists on every ordered table in this schema for one reason: several
 * records routinely share a millisecond, and `ORDER BY created_at` alone is then
 * a nondeterministic tie. The in-memory store gets insertion order for free from
 * array position, so without a monotonic tiebreak the two backends would
 * disagree under exactly the conditions a test creates. It is never exposed —
 * the domain types have no such field.
 */
export const approvals = pgTable(
  'approvals',
  {
    id: text('id').primaryKey(),
    seq: bigserial('seq', { mode: 'number' }).notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    action: text('action').$type<ActionType>().notNull(),
    severity: text('severity').$type<DriftSeverity>().notNull(),
    reasons: jsonb('reasons').$type<string[]>().notNull(),
    recommendedAction: text('recommended_action').notNull(),
    status: text('status').$type<ApprovalStatus>().notNull(),
    createdAt: bigint('created_at', { mode: 'number' }).notNull(),
    expiresAt: bigint('expires_at', { mode: 'number' }).notNull(),
    resolvedAt: bigint('resolved_at', { mode: 'number' }),
    resolvedBy: text('resolved_by'),
    channel: text('channel'),
  },
  (table) => [index('approvals_agent_status_idx').on(table.agentId, table.status, table.createdAt)],
);

/**
 * Loop 3: a single in-flight tool call awaiting a human.
 *
 * Deliberately NOT a reuse of `approvals` — that table is shaped entirely around
 * ActionType/DriftSeverity for agent-lifecycle control, and shoehorning a tool
 * name and call arguments into `reasons`/`recommended_action` would be lossy and
 * would mix two different kinds of event into one audit trail.
 *
 * A pending row here means a live HTTP request is blocked, so this is the most
 * latency-sensitive read in the system.
 */
export const toolCallApprovals = pgTable(
  'tool_call_approvals',
  {
    id: text('id').primaryKey(),
    seq: bigserial('seq', { mode: 'number' }).notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    tool: text('tool').notNull(),
    fieldPath: text('field_path'),
    matchedReason: text('matched_reason'),
    /**
     * Populated ONLY when payload capture is enabled — never leak a gated
     * field's actual value by default, that would defeat the point of gating it.
     */
    inputSummary: jsonb('input_summary').$type<Record<string, unknown>>(),
    status: text('status').$type<ApprovalStatus>().notNull(),
    createdAt: bigint('created_at', { mode: 'number' }).notNull(),
    expiresAt: bigint('expires_at', { mode: 'number' }).notNull(),
    resolvedAt: bigint('resolved_at', { mode: 'number' }),
    resolvedBy: text('resolved_by'),
    channel: text('channel'),
  },
  (table) => [
    index('tool_call_approvals_agent_status_idx').on(table.agentId, table.status, table.createdAt),
  ],
);

// --- history ----------------------------------------------------------------

/**
 * Drift verdicts over time. Uncapped, unlike the Redis and memory stores which
 * both truncate at 500 entries — durable ranged history is the entire reason
 * this backend exists.
 */
export const driftHistory = pgTable(
  'drift_history',
  {
    id: text('id').primaryKey(),
    seq: bigserial('seq', { mode: 'number' }).notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    at: bigint('at', { mode: 'number' }).notNull(),
    drift: boolean('drift').notNull(),
    severity: text('severity').$type<DriftSeverity>().notNull(),
    reasons: jsonb('reasons').$type<string[]>().notNull(),
    recommendedAction: text('recommended_action').notNull(),
    baselineTokenSpend: doublePrecision('baseline_token_spend').notNull(),
    currentTokenSpend: doublePrecision('current_token_spend').notNull(),
  },
  (table) => [index('drift_history_agent_at_idx').on(table.agentId, table.at)],
);

/** What Autopilot DID to an agent — distinct from `audit_events`, which is who CHANGED it. */
export const actionLog = pgTable(
  'action_log',
  {
    id: text('id').primaryKey(),
    seq: bigserial('seq', { mode: 'number' }).notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    at: bigint('at', { mode: 'number' }).notNull(),
    action: text('action').$type<ActionType>().notNull(),
    category: text('category').$type<ActionCategory>().notNull(),
    outcome: text('outcome').$type<ActionOutcome>().notNull(),
    reason: text('reason').notNull(),
    actor: text('actor'),
    channel: text('channel'),
  },
  (table) => [index('action_log_agent_at_idx').on(table.agentId, table.at)],
);

// --- credentials + audit ----------------------------------------------------

/**
 * Minted, scoped API keys. `hash` carries a unique index because it is the
 * authentication hot path: every authenticated request is one lookup on it.
 */
export const apiKeys = pgTable(
  'api_keys',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    name: text('name').notNull(),
    prefix: text('prefix').notNull(),
    /** sha256(token) as hex — see @driftwatch/sdk's api-keys.ts for why not a KDF. */
    hash: text('hash').notNull(),
    scopes: jsonb('scopes').$type<ApiKeyScope[]>().notNull(),
    /** Null/empty = fleet-wide. */
    agentIds: jsonb('agent_ids').$type<string[]>(),
    createdAt: bigint('created_at', { mode: 'number' }).notNull(),
    createdBy: text('created_by').notNull(),
    lastUsedAt: bigint('last_used_at', { mode: 'number' }),
    expiresAt: bigint('expires_at', { mode: 'number' }),
    /** Soft revoke: the row stays so the audit trail can still resolve id -> name. */
    revokedAt: bigint('revoked_at', { mode: 'number' }),
    revokedBy: text('revoked_by'),
  },
  (table) => [
    uniqueIndex('api_keys_hash_idx').on(table.hash),
    index('api_keys_org_idx').on(table.organizationId, table.createdAt),
  ],
);

/**
 * Every control-plane mutation worth attributing to a principal.
 *
 * `summary` MUST NOT contain secret plaintext: for a change that touches a
 * secret, name the FIELD that changed, never its before/after value.
 */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: text('id').primaryKey(),
    seq: bigserial('seq', { mode: 'number' }).notNull(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    at: bigint('at', { mode: 'number' }).notNull(),
    actor: text('actor').notNull(),
    actorLabel: text('actor_label').notNull(),
    action: text('action').$type<AuditAction>().notNull(),
    target: text('target'),
    agentId: text('agent_id'),
    summary: text('summary').notNull(),
  },
  (table) => [
    index('audit_events_at_idx').on(table.at),
    index('audit_events_agent_at_idx').on(table.agentId, table.at),
  ],
);

// --- coordination -----------------------------------------------------------

/**
 * Action-storm suppression, per (agent, key).
 *
 * In Redis this was SET NX PX; here it is an upsert whose WHERE clause makes the
 * check-and-set a single atomic statement — see PostgresStateStore. Expired rows
 * are overwritten in place rather than swept, so this table's size is bounded by
 * the number of distinct keys, not by time.
 */
export const cooldowns = pgTable(
  'cooldowns',
  {
    agentId: text('agent_id').notNull(),
    key: text('key').notNull(),
    expiresAt: bigint('expires_at', { mode: 'number' }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.agentId, table.key] })],
);

/**
 * Best-effort leader election so only one process runs a drift cycle.
 *
 * Global, not per-agent: one leader runs the whole fleet's cycle per tick.
 * `holder` is diagnostic only — the lock is won by the atomic upsert, never by
 * comparing this value.
 */
export const leaderLocks = pgTable('leader_locks', {
  key: text('key').primaryKey(),
  expiresAt: bigint('expires_at', { mode: 'number' }).notNull(),
  holder: text('holder'),
});

// --- run summaries ----------------------------------------------------------

/**
 * One row per agent task run — the durable telemetry record that lets the
 * console show charts without Grafana, and lets `SqlMetricsSource` answer the
 * drift detector's window queries without Prometheus.
 *
 * Deliberately a SUMMARY, not raw spans. A span table would need partitioning
 * and a retention policy to survive real throughput, and would push the
 * deployment back toward ClickHouse/Tempo — exactly the multi-container
 * complexity this architecture is removing. One row per run instead of ~50
 * spans answers the operator questions ("what did this cost, what did it call,
 * did it fail") at a fraction of the write volume. Full distributed tracing
 * remains available to anyone exporting OTLP to a real trace backend, and
 * `traceId` is kept here so a run links straight to it.
 */
export const agentRuns = pgTable(
  'agent_runs',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    startedAt: bigint('started_at', { mode: 'number' }).notNull(),
    endedAt: bigint('ended_at', { mode: 'number' }),
    durationMs: integer('duration_ms'),
    status: text('status').$type<'running' | 'completed' | 'failed' | 'stopped'>().notNull(),
    /** Why a run ended early: a guardrail breach, a tool denial, a model error. */
    stopReason: text('stop_reason'),
    errorMessage: text('error_message'),
    model: text('model'),
    steps: integer('steps'),
    promptTokens: integer('prompt_tokens'),
    completionTokens: integer('completion_tokens'),
    totalTokens: integer('total_tokens'),
    costUsd: doublePrecision('cost_usd'),
    /** Tool names called, in order, with per-call duration and outcome. */
    toolCalls: jsonb('tool_calls').$type<
      { tool: string; durationMs: number; ok: boolean; gated?: boolean }[]
    >(),
    /** Links to the full trace in whatever OTLP backend the deployment uses. */
    traceId: text('trace_id'),
  },
  (table) => [
    index('agent_runs_agent_started_idx').on(table.agentId, table.startedAt),
    index('agent_runs_started_idx').on(table.startedAt),
  ],
);

/**
 * Individual tool calls, extracted from runs so window queries can aggregate
 * latency and error rate per tool without unpacking every run's JSON.
 *
 * This is the table `SqlMetricsSource` reads to produce `WindowStats` — the
 * same shape `PrometheusMetricsSource` produces from PromQL, which is what
 * makes Prometheus optional rather than required.
 */
export const toolCallEvents = pgTable(
  'tool_call_events',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    runId: text('run_id'),
    tool: text('tool').notNull(),
    at: bigint('at', { mode: 'number' }).notNull(),
    durationMs: doublePrecision('duration_ms').notNull(),
    ok: boolean('ok').notNull(),
    /** True when a Loop 3 policy gated this call (denied or held for approval). */
    gated: boolean('gated').notNull().default(false),
  },
  (table) => [
    index('tool_call_events_agent_at_idx').on(table.agentId, table.at),
    index('tool_call_events_agent_tool_at_idx').on(table.agentId, table.tool, table.at),
  ],
);

/**
 * Model-switch events, counted by the drift detector so a behavior change can be
 * attributed to an intentional switch rather than organic drift. Mirrors the
 * `agent.model.switches` counter that `PrometheusMetricsSource` queries.
 */
export const modelSwitches = pgTable(
  'model_switches',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organizations.id),
    agentId: text('agent_id').notNull(),
    at: bigint('at', { mode: 'number' }).notNull(),
    fromModel: text('from_model'),
    toModel: text('to_model'),
  },
  (table) => [index('model_switches_agent_at_idx').on(table.agentId, table.at)],
);
